---
- hosts: all

  # These next two are some tricks b/c some EC2 machines don't have python, the monsters
  gather_facts: False
  
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      tags:
        - always
    - setup:
  

  tasks:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
      tags:
        packages


    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      tags:
        packages
        
    - name: install required packages
      package: name={{ item }} state=latest update_cache=yes
      with_items:
        - byobu
        - haproxy
        - xinetd
      tags:
        packages

    - name: setup haproxy config
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify:
        - restart haproxy

    - name: create lb folder
      file:
        path: "/opt/lb"
        owner: root
        group: root
        state: directory
        mode: 0775


    - name: create pow folder
      file:
        path: "/opt/pow"
        owner: root
        group: root
        state: directory
        mode: 0775

    - name: copy pow
      copy:
        src: powserver.py
        dest: /opt/pow/powserver.py
        owner: root
        group: root
        mode: 0775

    - name: copy lb-frontend
      copy:
        src: lb-frontend.sh
        dest: /opt/lb/lb-frontend.sh
        owner: root
        group: root
        mode: 0775

    - name: install xinet.d config
      copy:
        src: lb-frontend.config
        dest: /etc/xinetd.d/lb-frontend
        owner: root
        group: root
        mode: 0664
      notify:
        - restart xinetd
        
        
        

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted

    - name: restart xinetd
      service: name=xinetd state=restarted
      
